// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(pdf_inspectorFFI)
import pdf_inspectorFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pdf_inspector_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pdf_inspector_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePdfInspectorInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct FfiLayoutComplexity: Equatable, Hashable {
    /**
     * True if any page has tables or multi-column text.
     */
    public var isComplex: Bool
    /**
     * 1-indexed pages where table borders were detected.
     */
    public var pagesWithTables: [UInt32]
    /**
     * 1-indexed pages where 2+ text columns were detected.
     */
    public var pagesWithColumns: [UInt32]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * True if any page has tables or multi-column text.
         */isComplex: Bool, 
        /**
         * 1-indexed pages where table borders were detected.
         */pagesWithTables: [UInt32], 
        /**
         * 1-indexed pages where 2+ text columns were detected.
         */pagesWithColumns: [UInt32]) {
        self.isComplex = isComplex
        self.pagesWithTables = pagesWithTables
        self.pagesWithColumns = pagesWithColumns
    }

    

    
}

#if compiler(>=6)
extension FfiLayoutComplexity: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiLayoutComplexity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiLayoutComplexity {
        return
            try FfiLayoutComplexity(
                isComplex: FfiConverterBool.read(from: &buf), 
                pagesWithTables: FfiConverterSequenceUInt32.read(from: &buf), 
                pagesWithColumns: FfiConverterSequenceUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiLayoutComplexity, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.isComplex, into: &buf)
        FfiConverterSequenceUInt32.write(value.pagesWithTables, into: &buf)
        FfiConverterSequenceUInt32.write(value.pagesWithColumns, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiLayoutComplexity_lift(_ buf: RustBuffer) throws -> FfiLayoutComplexity {
    return try FfiConverterTypeFfiLayoutComplexity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiLayoutComplexity_lower(_ value: FfiLayoutComplexity) -> RustBuffer {
    return FfiConverterTypeFfiLayoutComplexity.lower(value)
}


public struct FfiPageOcrReasons: Equatable, Hashable {
    /**
     * 1-indexed page number.
     */
    public var page: UInt32
    /**
     * Machine-readable OCR reason identifiers.
     */
    public var reasons: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * 1-indexed page number.
         */page: UInt32, 
        /**
         * Machine-readable OCR reason identifiers.
         */reasons: [String]) {
        self.page = page
        self.reasons = reasons
    }

    

    
}

#if compiler(>=6)
extension FfiPageOcrReasons: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPageOcrReasons: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPageOcrReasons {
        return
            try FfiPageOcrReasons(
                page: FfiConverterUInt32.read(from: &buf), 
                reasons: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPageOcrReasons, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.page, into: &buf)
        FfiConverterSequenceString.write(value.reasons, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPageOcrReasons_lift(_ buf: RustBuffer) throws -> FfiPageOcrReasons {
    return try FfiConverterTypeFfiPageOcrReasons.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPageOcrReasons_lower(_ value: FfiPageOcrReasons) -> RustBuffer {
    return FfiConverterTypeFfiPageOcrReasons.lower(value)
}


public struct FfiPdfClassification: Equatable, Hashable {
    /**
     * The detected PDF type.
     */
    public var pdfType: FfiPdfType
    /**
     * Total number of pages.
     */
    public var pageCount: UInt32
    /**
     * 0-indexed page numbers that need OCR.
     */
    public var pagesNeedingOcr: [UInt32]
    /**
     * Detection confidence (0.0-1.0).
     */
    public var confidence: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The detected PDF type.
         */pdfType: FfiPdfType, 
        /**
         * Total number of pages.
         */pageCount: UInt32, 
        /**
         * 0-indexed page numbers that need OCR.
         */pagesNeedingOcr: [UInt32], 
        /**
         * Detection confidence (0.0-1.0).
         */confidence: Float) {
        self.pdfType = pdfType
        self.pageCount = pageCount
        self.pagesNeedingOcr = pagesNeedingOcr
        self.confidence = confidence
    }

    

    
}

#if compiler(>=6)
extension FfiPdfClassification: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPdfClassification: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPdfClassification {
        return
            try FfiPdfClassification(
                pdfType: FfiConverterTypeFfiPdfType.read(from: &buf), 
                pageCount: FfiConverterUInt32.read(from: &buf), 
                pagesNeedingOcr: FfiConverterSequenceUInt32.read(from: &buf), 
                confidence: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPdfClassification, into buf: inout [UInt8]) {
        FfiConverterTypeFfiPdfType.write(value.pdfType, into: &buf)
        FfiConverterUInt32.write(value.pageCount, into: &buf)
        FfiConverterSequenceUInt32.write(value.pagesNeedingOcr, into: &buf)
        FfiConverterFloat.write(value.confidence, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPdfClassification_lift(_ buf: RustBuffer) throws -> FfiPdfClassification {
    return try FfiConverterTypeFfiPdfClassification.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPdfClassification_lower(_ value: FfiPdfClassification) -> RustBuffer {
    return FfiConverterTypeFfiPdfClassification.lower(value)
}


public struct FfiPdfResult: Equatable, Hashable {
    /**
     * The detected PDF type.
     */
    public var pdfType: FfiPdfType
    /**
     * Markdown output (None if detect-only or scanned PDF).
     */
    public var markdown: String?
    /**
     * Total number of pages.
     */
    public var pageCount: UInt32
    /**
     * Processing time in milliseconds.
     */
    public var processingTimeMs: UInt64
    /**
     * 1-indexed page numbers that need OCR.
     */
    public var pagesNeedingOcr: [UInt32]
    /**
     * Machine-readable OCR reasons by 1-indexed page.
     */
    public var ocrReasonsByPage: [FfiPageOcrReasons]
    /**
     * Title from PDF metadata.
     */
    public var title: String?
    /**
     * Detection confidence (0.0-1.0).
     */
    public var confidence: Float
    /**
     * Layout complexity analysis (tables, multi-column detection).
     */
    public var layout: FfiLayoutComplexity
    /**
     * Whether encoding issues were detected.
     */
    public var hasEncodingIssues: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The detected PDF type.
         */pdfType: FfiPdfType, 
        /**
         * Markdown output (None if detect-only or scanned PDF).
         */markdown: String?, 
        /**
         * Total number of pages.
         */pageCount: UInt32, 
        /**
         * Processing time in milliseconds.
         */processingTimeMs: UInt64, 
        /**
         * 1-indexed page numbers that need OCR.
         */pagesNeedingOcr: [UInt32], 
        /**
         * Machine-readable OCR reasons by 1-indexed page.
         */ocrReasonsByPage: [FfiPageOcrReasons], 
        /**
         * Title from PDF metadata.
         */title: String?, 
        /**
         * Detection confidence (0.0-1.0).
         */confidence: Float, 
        /**
         * Layout complexity analysis (tables, multi-column detection).
         */layout: FfiLayoutComplexity, 
        /**
         * Whether encoding issues were detected.
         */hasEncodingIssues: Bool) {
        self.pdfType = pdfType
        self.markdown = markdown
        self.pageCount = pageCount
        self.processingTimeMs = processingTimeMs
        self.pagesNeedingOcr = pagesNeedingOcr
        self.ocrReasonsByPage = ocrReasonsByPage
        self.title = title
        self.confidence = confidence
        self.layout = layout
        self.hasEncodingIssues = hasEncodingIssues
    }

    

    
}

#if compiler(>=6)
extension FfiPdfResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPdfResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPdfResult {
        return
            try FfiPdfResult(
                pdfType: FfiConverterTypeFfiPdfType.read(from: &buf), 
                markdown: FfiConverterOptionString.read(from: &buf), 
                pageCount: FfiConverterUInt32.read(from: &buf), 
                processingTimeMs: FfiConverterUInt64.read(from: &buf), 
                pagesNeedingOcr: FfiConverterSequenceUInt32.read(from: &buf), 
                ocrReasonsByPage: FfiConverterSequenceTypeFfiPageOcrReasons.read(from: &buf), 
                title: FfiConverterOptionString.read(from: &buf), 
                confidence: FfiConverterFloat.read(from: &buf), 
                layout: FfiConverterTypeFfiLayoutComplexity.read(from: &buf), 
                hasEncodingIssues: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPdfResult, into buf: inout [UInt8]) {
        FfiConverterTypeFfiPdfType.write(value.pdfType, into: &buf)
        FfiConverterOptionString.write(value.markdown, into: &buf)
        FfiConverterUInt32.write(value.pageCount, into: &buf)
        FfiConverterUInt64.write(value.processingTimeMs, into: &buf)
        FfiConverterSequenceUInt32.write(value.pagesNeedingOcr, into: &buf)
        FfiConverterSequenceTypeFfiPageOcrReasons.write(value.ocrReasonsByPage, into: &buf)
        FfiConverterOptionString.write(value.title, into: &buf)
        FfiConverterFloat.write(value.confidence, into: &buf)
        FfiConverterTypeFfiLayoutComplexity.write(value.layout, into: &buf)
        FfiConverterBool.write(value.hasEncodingIssues, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPdfResult_lift(_ buf: RustBuffer) throws -> FfiPdfResult {
    return try FfiConverterTypeFfiPdfResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPdfResult_lower(_ value: FfiPdfResult) -> RustBuffer {
    return FfiConverterTypeFfiPdfResult.lower(value)
}


public 
enum FfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Msg(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Msg(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Msg(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}



public enum FfiPdfType: Equatable, Hashable {
    
    case textBased
    case scanned
    case imageBased
    case mixed





}

#if compiler(>=6)
extension FfiPdfType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPdfType: FfiConverterRustBuffer {
    typealias SwiftType = FfiPdfType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPdfType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .textBased
        
        case 2: return .scanned
        
        case 3: return .imageBased
        
        case 4: return .mixed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiPdfType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .textBased:
            writeInt(&buf, Int32(1))
        
        
        case .scanned:
            writeInt(&buf, Int32(2))
        
        
        case .imageBased:
            writeInt(&buf, Int32(3))
        
        
        case .mixed:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPdfType_lift(_ buf: RustBuffer) throws -> FfiPdfType {
    return try FfiConverterTypeFfiPdfType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPdfType_lower(_ value: FfiPdfType) -> RustBuffer {
    return FfiConverterTypeFfiPdfType.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiPageOcrReasons: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPageOcrReasons]

    public static func write(_ value: [FfiPageOcrReasons], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPageOcrReasons.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPageOcrReasons] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPageOcrReasons]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiPageOcrReasons.read(from: &buf))
        }
        return seq
    }
}
/**
 * Lightweight PDF classification for routing decisions.
 */
public func classifyPdf(path: String)throws  -> FfiPdfClassification  {
    return try  FfiConverterTypeFfiPdfClassification_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
        uniffiCallStatus in
    uniffi_pdf_inspector_fn_func_classify_pdf(
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}
/**
 * Lightweight PDF classification from bytes.
 */
public func classifyPdfBytes(data: Data)throws  -> FfiPdfClassification  {
    return try  FfiConverterTypeFfiPdfClassification_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
        uniffiCallStatus in
    uniffi_pdf_inspector_fn_func_classify_pdf_bytes(
        FfiConverterData.lower(data),uniffiCallStatus
    )
})
}
/**
 * Fast detection only — no text extraction or markdown.
 */
public func detectPdf(path: String)throws  -> FfiPdfResult  {
    return try  FfiConverterTypeFfiPdfResult_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
        uniffiCallStatus in
    uniffi_pdf_inspector_fn_func_detect_pdf(
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}
/**
 * Fast detection from bytes — no text extraction or markdown.
 */
public func detectPdfBytes(data: Data)throws  -> FfiPdfResult  {
    return try  FfiConverterTypeFfiPdfResult_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
        uniffiCallStatus in
    uniffi_pdf_inspector_fn_func_detect_pdf_bytes(
        FfiConverterData.lower(data),uniffiCallStatus
    )
})
}
/**
 * Extract plain text from a PDF file.
 */
public func extractText(path: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
        uniffiCallStatus in
    uniffi_pdf_inspector_fn_func_extract_text(
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}
/**
 * Extract plain text from PDF bytes.
 */
public func extractTextBytes(data: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
        uniffiCallStatus in
    uniffi_pdf_inspector_fn_func_extract_text_bytes(
        FfiConverterData.lower(data),uniffiCallStatus
    )
})
}
/**
 * Process a PDF file: detect type, extract text, and convert to Markdown.
 */
public func processPdf(path: String)throws  -> FfiPdfResult  {
    return try  FfiConverterTypeFfiPdfResult_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
        uniffiCallStatus in
    uniffi_pdf_inspector_fn_func_process_pdf(
        FfiConverterString.lower(path),uniffiCallStatus
    )
})
}
/**
 * Process a PDF from bytes in memory.
 */
public func processPdfBytes(data: Data)throws  -> FfiPdfResult  {
    return try  FfiConverterTypeFfiPdfResult_lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
        uniffiCallStatus in
    uniffi_pdf_inspector_fn_func_process_pdf_bytes(
        FfiConverterData.lower(data),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pdf_inspector_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pdf_inspector_checksum_func_classify_pdf() != 59618) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pdf_inspector_checksum_func_classify_pdf_bytes() != 48216) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pdf_inspector_checksum_func_detect_pdf() != 52236) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pdf_inspector_checksum_func_detect_pdf_bytes() != 6602) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pdf_inspector_checksum_func_extract_text() != 57092) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pdf_inspector_checksum_func_extract_text_bytes() != 64765) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pdf_inspector_checksum_func_process_pdf() != 16101) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pdf_inspector_checksum_func_process_pdf_bytes() != 54732) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePdfInspectorInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all